#35  클라우드센터 가상머신 상태 UI
ablecloud-team/ablestack-cockpit-plugin pull request #76
Opened 2021-03-18 09:04 UTC by ycyun

- [ ] 클라우드센터 가상머신 동작상태
- [ ] 클라우드센터 가상머신 시작, 정지 관리
- [ ] 클라우드센터 가상머신 삭제
   [천강타책임](@kt-cheon)의 pcs 관리 명령어를 사용하여 위 기능들 UI에 연결
- [ ] 클라우드센터 가상머신 CPU, Memony등의 표시
   pcs를 사용해 어떤 호스트에 VM이 올라가있는지 확인후 해당 VM의 자원 할당량 표시

2021-03-23 03:28 UTC, ycyun commented
시작 및 정지는 클러스터 시작, 중지에 포함된 내용이라 생략합니다.

2021-03-23 04:23 UTC, dhslove requested changes

2021-03-23 04:23 UTC, dhslove commented on python/host/virshedit.py
> +#!/usr/bin/env python3
아래의 형식으로 주석 작성 바랍니다. 

'''
Copyright (c) 2021 ABLECLOUD Co. Ltd.

프로그램의 전체 내용 설명

최초작성일 : yyyy-mm-dd
'''

2021-03-23 04:23 UTC, dhslove commented on python/host/virshedit.py
> +def createArgumentParser():
함수의 주석은 함수 선언부 위에 작성합니다. 예를 들어

"""
설명

파라미터 설명 : 
반환값 : 
"""
def createArgumentParser():

2021-03-23 04:23 UTC, dhslove commented on python/host/virshedit.py
> +
함수 주석 넣어주세요.

2021-03-23 04:23 UTC, dhslove commented on python/host/virshlist.py
> +#!/usr/bin/python3
파일 시작부 주석 넣어주세요.

"""
Copyright (c) 2021 ABLECLOUD Co. Ltd.

프로그램의 전체 내용 설명

최초작성일 : yyyy-mm-dd
"""

2021-03-23 04:23 UTC, dhslove commented on src/features/cloud-center-virtual-machine.js
> +// import spawn from "../../../base1/cockpit.js"
파일 상단 주석 넣어주세요.

Copyright (c) 2021 ABLECLOUD Co. Ltd.

프로그램의 전체 내용 설명
최초작성일 : yyyy-mm-dd

2021-03-23 04:23 UTC, dhslove commented on src/features/cloud-center-virtual-machine.js
> +    constructor() {
모든 함수 선언부에 주석 넣어 주세요.

2021-03-24 23:38 UTC, dhslove approved these changes

2021-03-24 23:39 UTC, merged