Sc cluster status
ablecloud-team/ablestack-cockpit-plugin pull request #77
Opened 2021-03-19 00:59 UTC by jschoiRR

스토리지 클러스터 상태 조회 화면 개발 

- [ ] 스토리지센터 클러스터상태 UI[html, js] 
- [ ] 유지보수 모드 상태 변경 기능[python] 
- [ ] 스토리지센터 클러스터 상태를 조회

* 현재 이슈
실제 구성되어 있는 ceph 스토리지가 없어  ceph -s시 확인할수 없음
ceph -s 시 출력되는 메시지를 임시 텍스트 파일로 생성하여 테스트 수행중이며
실제 ceph 스토리지 구성 후 로직 테스트 필요

#26 #23 #22

2021-03-19 01:02 UTC, ycyun commented
ceph -s -f json-pretty 나
ceph -s -f json 으로 호출하면 출력값 자체가 json으로 나옵니다.

2021-03-21 23:59 UTC, jschoiRR commented
> ceph -s -f json-pretty 나
> ceph -s -f json 으로 호출하면 출력값 자체가 json으로 나옵니다.

 임시로 보

2021-03-29 01:43 UTC, jschoiRR commented
리뷰요청드립니다.

2021-03-29 04:50 UTC, dhslove requested changes

2021-03-29 04:50 UTC, dhslove commented on python/storage_center_cluster_status/scc_status_detail.py
> +import sys
다음 내용의 파일 시작 주석 추가 바랍니다. 

```
# Copyright (c) 2021 ABLECLOUD Co. Ltd

# 파일의 목적 내용 등 요약
# 최초 작성일 : yyyy-mm-dd
```

2021-03-29 04:50 UTC, dhslove commented on python/storage_center_cluster_status/scc_status_detail.py
> +
함수 주석 형식을 통일해 주세요. 

(''') 주석 사용을 원칙으로 합니다. 

statusDeteil -> statusDetail 로 변경해 주세요.

그리고 함수 내부에서 어떤 일을 하는 것인지 주석이 좀 추가되면 좋겠습니다. 
또한 내용을 구분하기 위한 줄은 1줄로 통일해주세요. 2~4줄사이의 간격을 사용하지 말고. 줄을 많이 띄는 이유는 구분하기 위한 것 같은데 그 부분을 주석으로 내용을 설명하면서 구분하면 더 좋을 것 같습니다.

2021-03-29 04:50 UTC, dhslove commented on python/storage_center_cluster_status/scc_status_update.py
> +#!/usr/bin/env python3
다음 내용의 파일 시작 주석 추가 바랍니다.
```
# Copyright (c) 2021 ABLECLOUD Co. Ltd

# 파일의 목적 내용 등 요약
# 최초 작성일 : yyyy-mm-dd
```

2021-03-29 04:50 UTC, dhslove commented on python/storage_center_cluster_status/scc_status_update.py
> +
함수 주석 형식을 통일해 주세요. 

(''') 주석 사용을 원칙으로 합니다. 

그리고 함수 내부에서 어떤 일을 하는 것인지 주석이 좀 추가되면 좋겠습니다. 
또한 내용을 구분하기 위한 줄은 1줄로 통일해주세요. 2~4줄사이의 간격을 사용하지 말고. 줄을 많이 띄는 이유는 구분하기 위한 것 같은데 그 부분을 주석으로 내용을 설명하면서 구분하면 더 좋을 것 같습니다.

2021-03-29 04:50 UTC, dhslove commented on python/storage_center_vm_status/scvm_status_detail.py
> +
함수 주석 형식을 통일해 주세요. 

(''') 주석 사용을 원칙으로 합니다. 

statusDeteil -> statusDetail 로 변경해 주세요.

그리고 함수 내부에서 어떤 일을 하는 것인지 주석이 좀 추가되면 좋겠습니다. 
또한 내용을 구분하기 위한 줄은 1줄로 통일해주세요. 2~4줄사이의 간격을 사용하지 말고. 줄을 많이 띄는 이유는 구분하기 위한 것 같은데 그 부분을 주석으로 내용을 설명하면서 구분하면 더 좋을 것 같습니다.

2021-03-29 04:50 UTC, dhslove commented on python/storage_center_vm_status/scvm_status_update.py
> +
함수 주석 형식을 통일해 주세요. 

(''') 주석 사용을 원칙으로 합니다. 

그리고 함수 내부에서 어떤 일을 하는 것인지 주석이 좀 추가되면 좋겠습니다. 
또한 내용을 구분하기 위한 줄은 1줄로 통일해주세요. 2~4줄사이의 간격을 사용하지 말고. 줄을 많이 띄는 이유는 구분하기 위한 것 같은데 그 부분을 주석으로 내용을 설명하면서 구분하면 더 좋을 것 같습니다.

2021-03-29 04:50 UTC, dhslove commented on src/features/main.js
> +
각 작업마다 주석 충실하게...

그리고 줄 공간 너무 많이 떨어뜨리지 않고 한줄로. 구분을 하고 싶으면 주석표기

2021-03-29 04:50 UTC, dhslove commented on src/features/storage-vm-status-update.js
> +
각 작업마다 주석 충실하게...

그리고 줄 공간 너무 많이 떨어뜨리지 않고 한줄로. 구분을 하고 싶으면 주석표기

2021-03-29 07:31 UTC, dhslove approved these changes

2021-03-29 07:31 UTC, merged